import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";
import { Analytics } from '@vercel/analytics/next';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { fontMono, fontSans } from "@/lib/fonts"
import AuthProvider from '@/layout/AuthProvider';
import GlobalProvider from '@/layout/GlobalProvider';

import "@iconbox/ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        <NuqsAdapter>
          <GlobalProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
          </GlobalProvider>
        </NuqsAdapter>
        <Analytics />
      </body>
    </html>
  );
}

export default RootLayout;
