import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";
import { Analytics } from '@vercel/analytics/next';

import { ThemeProvider } from "@/components/theme/theme-provider"
import { fontMono, fontSans } from "@/lib/fonts"
import AuthProvider from '@/layout/AuthProvider';

import "@iconbox/ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {children}
          </AuthProvider>
        </ThemeProvider>
        
        <Analytics />
      </body>
    </html>
  );
}

export default RootLayout;
